### ISSUE TITLE
Gift Card Created Email - this.giftCardService_ is undefined on ses.js

### ISSUE THREAD

**Issue by Douglas-Pontes** [pevey/medusa-plugin-ses#4]
When I test to send the email via postman It works like a charm, but when I go to the admin dashboard and create a gift card it tries to send the email but I get this problem Cannot read properties of undefined (reading 'retrieve') at ses.js file on line 589 const giftCard = await this.giftCardService_.retrieve(id, {, that means this.giftCardService_ is undefined. I console log the id and its right, I think the problem is the dependency injection of this service

<img width="959" alt="image" src="https://github.com/pevey/medusa-plugin-ses/assets/42808145/1b2051d4-0b5a-48b1-a91f-a96650e18dab">

```
PACKAGE JSON
"dependencies": {
    "@medusajs/admin": "^7.1.3",
    "@medusajs/cache-inmemory": "^1.8.8",
    "@medusajs/cache-redis": "^1.8.8",
    "@medusajs/event-bus-local": "^1.9.6",
    "@medusajs/event-bus-redis": "^1.8.9",
    "@medusajs/icons": "^1.0.1",
    "@medusajs/inventory": "^1.10.0",
    "@medusajs/medusa": "^1.17.0",
    "@medusajs/stock-location": "^1.10.0",
    "@medusajs/ui": "^2.0.0",
    "@tanstack/react-query": "4.22.0",
    "babel-preset-medusa-package": "^1.1.19",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "dotenv": "16.0.3",
    "express": "^4.17.2",
    "medusa-file-gcs": "^0.1.0",
    "medusa-fulfillment-manual": "^1.1.38",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-paypal": "^6.0.2",
    "medusa-payment-stripe": "^6.0.5",
    "medusa-plugin-meilisearch": "^2.0.10",
    "medusa-plugin-ses": "^2.2.3",
    "medusa-plugin-variant-images": "^1.0.3",
    "prism-react-renderer": "^2.0.4",
    "typeorm": "^0.3.16"
  },
  "devDependencies": {
    "@babel/cli": "^7.14.3",
    "@babel/core": "^7.14.3",
    "@babel/preset-typescript": "^7.21.4",
    "@medusajs/medusa-cli": "^1.3.21",
    "@types/express": "^4.17.13",
    "@types/jest": "^27.4.0",
    "@types/node": "^17.0.8",
    "babel-preset-medusa-package": "^1.1.19",
    "cross-env": "^7.0.3",
    "eslint": "^6.8.0",
    "jest": "^27.3.1",
    "mongoose": "^5.13.14",
    "rimraf": "^3.0.2",
    "ts-jest": "^27.0.7",
    "ts-loader": "^9.2.6",
    "typescript": "^4.5.2"
  },

MEDUSA CONFIG PLUGIN
{
    resolve: "medusa-plugin-ses",
    options: {
      access_key_id: process.env.SES_ACCESS_KEY_ID,
      secret_access_key: process.env.SES_SECRET_ACCESS_KEY,
      region: process.env.SES_REGION,
      from: process.env.SES_FROM,
      template_path: process.env.SES_TEMPLATE_PATH,
      partial_path: process.env.SES_PARTIAL_PATH,
      enable_endpoint: process.env.SES_ENABLE_ENDPOINT,
      enable_sim_mode: process.env.SES_ENABLE_SIM_MODE,
      gift_card_created_template: 'gift_card_created',
      // order_placed_template: 'order_placed',
      // order_shipped_template: 'order_shipped',
      // customer_password_reset_template: 'customer_password_reset',
      //order_canceled_template: 'order_canceled',
      //order_refund_created_template: 'order_refund_created',
      //order_return_requested_template: 'order_return_requested',
      //order_items_returned_template: 'order_items_returned',
      //swap_created_template: 'swap_created',
      //swap_shipment_created_template: 'swap_shipment_created',
      //swap_received_template: 'swap_received',
      //claim_shipment_created_template: 'claim_shipment_created',
      //user_password_reset_template: 'user_password_reset',
      //medusa_restock_template: 'medusa_restock',
    }
  },
```

**Comment by pevey** [comment]
The gift card service was missing from the ses class constructor.  It has been fixed in development, but not officially released yet because the changes for the new version are extensive and still in testing.  

Could I get you to try updating to version ["3.0.1-canary.5"](https://www.npmjs.com/package/medusa-plugin-ses/v/3.0.1-canary.5) to see if that resolved the issue?

**Comment by pevey** [comment]
With the new version, you don't need to specify all the templates in your config.  Just specify your template and partials folders.  The templates must be named according to the default names to be recognized.  But the major benefit is that now a LOT more events are enabled for notifications by default, if a valid template is present.

**Comment by Douglas-Pontes** [comment]
Now we have the gift card service, but Im creating an gift card without an order related, so order is coming null, but in your code at ses.js:71 the email is required, but in this case you should be getting the email at metadata, like I believe we will only have an order related if someone uses the gift card right?
<img width="460" alt="image" src="https://github.com/pevey/medusa-plugin-ses/assets/42808145/0aea4911-cdde-44d1-865e-5fb0a211fe76">
<img width="717" alt="image" src="https://github.com/pevey/medusa-plugin-ses/assets/42808145/9b2c97ae-1cc6-46d4-867a-dbd5325b70bb">
<img width="1440" alt="image" src="https://github.com/pevey/medusa-plugin-ses/assets/42808145/db7850eb-7104-46da-8403-1bba8201eda9">
<img width="855" alt="image" src="https://github.com/pevey/medusa-plugin-ses/assets/42808145/7fa666eb-f61b-429f-ba60-c989dd60b437">

**Comment by Douglas-Pontes** [comment]
> With the new version, you don't need to specify all the templates in your config. Just specify your template and partials folders. The templates must be named according to the default names to be recognized. But the major benefit is that now a LOT more events are enabled for notifications by default, if a valid template is present.

Thats great nice job

**Comment by pevey** [comment]
Can you help me understand the flow a bit?  I've never used the gift card feature myself.

The even you are interested in is when an admin user creates new gift card using the admin app.  Is this correct?

Where should the email be sent in this case?  Is there a customer email address captured during this process?

**Comment by pevey** [comment]
I think I know how to fix it.  I'll let you know when I post a new canary version.

**Comment by Douglas-Pontes** [comment]
Actually I configured your plugin and the first event I tried to test was gift card, from what I understood medusa only sends an email when you create a custom gift card which you send to an specific email, which later when customer uses the gift card it will be checked if the customer has the same email, in this case at notification-data at line 93 you should get the email from metadata which will be the email you want to send the gift card to and also order can will be null at the time the email is sent

But I'm very new to medusa aswell, I can be wrong

**Comment by pevey** [comment]
I just published 3.0.1-canary.6.  Could you try it and see if it resolves your error?

**Comment by Douglas-Pontes** [comment]
not yet, you fixed the problem of email, but now its not finding the template I debbuged with console.log

for some reason in the templatePath we have node_modules before /data/templates in my project thats wrong

<img width="974" alt="image" src="https://github.com/pevey/medusa-plugin-ses/assets/42808145/ec0669de-9c27-4c08-ad3b-f79fa91cbb52">

<img width="784" alt="image" src="https://github.com/pevey/medusa-plugin-ses/assets/42808145/a790a0b2-8366-419e-9981-dc122d51ebf7">

SES_TEMPLATE_PATH="data/templates"

**Comment by Douglas-Pontes** [comment]
If I change the template path to be the whole path it works I got the email!
SES_TEMPLATE_PATH="/Users/douglas/Desktop/PmdTech Solutions/ecommerce/my-medusa-store/data/templates"

but you should fix that because in production thats bad

**Comment by pevey** [comment]
Hmm, this is a strange one.  Nothing about the template path was changed.

When I develop locally and use yarn link to install or install from a local folder, I have to use the full path (because of sym-linking weirdness.  But when I install from npm, I can use the relative path.  I'm not sure what might be causing this for you.

**Comment by pevey** [comment]
I will definitely test it more before 3.0 goes live.

**Comment by Douglas-Pontes** [comment]
Yeah me neither, I'll test all the events, and I'll keep opening issues if I find something else okay? for now I'll use .6 version and the whole path

**Comment by pevey** [comment]
Ah, I think I might know what has happened.  Thank you so much for surfacing this.  

With 3.0, it was converted to typescript.  As part of that, the build process was changed to put everything in the plugin's 'dist' folder instead of the top level folder like it was before.  This extra level is causing the issue.  I will fix it.

**Comment by Douglas-Pontes** [comment]
> Ah, I think I might know what has happened. Thank you so much for surfacing this.
> 
> With 3.0, it was converted to typescript. As part of that, the build process was changed to put everything in the 'dist' folder instead of the top level folder like it was before. This extra level is causing the issue. I will fix it.

Oh yeah, thats it, well done!!

So I'll get back with other issues if I find more okay? thank you for the quick answers, I hope I can help you more

**Comment by pevey** [comment]
I just pushed 3.0.1-canary.7

**Comment by Douglas-Pontes** [comment]
Nice @pevey It working with data/templates

Thanky youu
